const Discord = require("discord.js");
const bot = new Discord.Client();
const fs = require("fs")

module.exports = {
        name: "compliment",
        aliases: ["elogio"],
        description: "Você quer ser elogiado ?",
        ussage: "<prefix>compliment <mention>",
        category: "fun",
    run: async (client, message, args) => {
    let user = message.mentions.users.first();
    if (message.mentions.users === message.author.username) return message.reply('Você não pode se elogiar');
    if (message.mentions.users.size < 1) return message.reply('Você deve mencionar alguém para elogiá-los.')
    var roast = [
              "Seu sorriso é contagioso.",
              "Você está ótima hoje.",
              "Você é um biscoito inteligente.",
              "Aposto que você faz os bebês sorrirem.",
              "Você tem maneiras impecáveis.",
              "Eu gosto do seu estilo.",
              "Você tem a melhor risada.",
              "Eu gosto de você.",
              "Você é o mais perfeito que existe.",
              "Você é o suficiente.",
              "Você é forte.",
              "Sua perspectiva é refrescante.",
              "Você é um amigo incrível.",
              "Você ilumina a sala.",
              "Você brilha mais do que uma estrela cadente.",
              "Você merece um abraço agora.",
              "Você deve se orgulhar de si mesmo.",
              "Você é mais útil do que imagina.",
              "Você tem um ótimo senso de humor.",
              "Você tem todos os movimentos certos!",
              "Essa é sua foto ao lado de 'charmoso' no dicionário?",
              "Sua bondade é um bálsamo para todos que a encontram.",
              "Você é tudo isso e um saco enorme de batatas fritas.",
              "Em uma escala de 1 a 10, você é um 11.",
              "Você é corajoso.",
              "Você é ainda mais bonita por dentro do que por fora.",
              "Você tem a coragem de suas convicções.",
              "Seus olhos são de tirar o fôlego.",
              "Se os pássaros azuis dos desenhos animados fossem reais, muitos deles estariam sentados em seus ombros, cantando agora.",
              "Você está fazendo a diferença.",
              "Você é como o sol em um dia chuvoso.",
              "Você traz o melhor para as outras pessoas.",
              "Sua capacidade de recuperar factóides aleatórios no momento certo é impressionante.",
              "Você é um ótimo ouvinte.",
              "Como é que você sempre fica ótima, mesmo em calças de moletom?",
              "Tudo seria melhor se mais pessoas fossem como você!",
              "Eu aposto que você suou glitter.",
              "Você era legal antes dos descolados serem legais.",
              "Essa cor é perfeita para você.",
              "Sair com você é sempre uma explosão.",
              "Você sempre sabe - e diz - exatamente o que preciso ouvir quando preciso ouvir.",
              "Você cheira muito bem.",
              "Você pode dançar como ninguém está assistindo, mas todo mundo está assistindo porque você é uma dançarina incrível!",
              "Estar perto de você melhora tudo!",
              "Quando você diz 'eu pretendia fazer isso', eu acredito totalmente em você.",
              "Quando você não tem medo de ser você mesmo, é o mais incrível.",
              "As cores parecem mais brilhantes quando você está por perto.",
              "Você é mais divertido do que uma bola cheia de doces. (E sério, o que poderia ser mais divertido que isso?)",
              "O que você não gosta em si mesmo é o que o torna tão interessante.",
              "Você é maravilhoso.",
              "Você tem cotovelos fofos. De verdade!",
              "As piadas são mais engraçadas quando você conta.",
              "Você é melhor do que uma casquinha de sorvete de três bolas. Com granulado.",
              "Seu umbigo é meio adorável.",
              "Seu cabelo está deslumbrante.",
              "Você é único!",
              "Você é inspirador.",
              "Se você fosse uma caixa de giz de cera, seria a marca gigante com o apontador embutido.",
              "Você deveria ser agradecido com mais frequência. Então, obrigado !!",
              "Nossa comunidade é melhor porque você está nela.",
              "Alguém está passando por algo difícil agora, porque você tem as costas deles.",
              "Você tem as melhores idéias.",
              "Você sempre sabe encontrar esse revestimento prateado.",
              "Todo mundo é derrubado às vezes, mas você sempre se levanta e continua.",
              "Você é uma vela na escuridão.",
              "Você é um ótimo exemplo para os outros.",
              "Estar perto de você é como estar de férias felizes.",
              "Você sempre sabe exatamente o que dizer.",
              "Você está sempre aprendendo coisas novas e tentando melhorar a si mesmo, o que é incrível.",
              "Se alguém baseasse um meme da Internet em você, teria uma gramática impecável.",
              "Você poderia sobreviver a um apocalipse zumbi.",
              "Você é mais divertido do que plástico bolha.",
              "Quando você comete um erro, você o corrige.",
              "Quem te criou? Eles merecem uma medalha por um trabalho bem feito.",
              "Você é ótimo em descobrir coisas.",
              "Sua voz é magnífica.",
              "As pessoas que você ama têm sorte de ter você em suas vidas.",
              "Você é como uma lufada de ar fresco.",
              "Você é linda - e isso é a coisa menos interessante sobre você também.",
              "Você é tão atencioso.",
              "Seu potencial criativo parece ilimitado.",
              "Seu nome combina com você com um T.",
              "Você é irresistível quando cora.",
              "As ações falam mais alto que as palavras, e as suas contam uma história incrível.",
              "De alguma forma, você faz o tempo parar e voar ao mesmo tempo.",
              "Quando você decide algo, nada fica no seu caminho.",
              "Você parece realmente saber quem você é.",
              "Qualquer equipe teria sorte em ter você nele.",
              "No ensino médio, aposto que você foi votado como 'mais provável de continuar sendo incrível.'",
              "Aposto que você faz as palavras cruzadas com tinta.",
              "Bebês e pequenos animais provavelmente"
]
    const roasts = roast[Math.floor(Math.random() * roast.length)];
    const embed = new Discord.RichEmbed()
        .setColor(0x00A2E8)
        .setDescription(user.username + ", " + roasts);
    message.channel.send({embed})
  }
}
